/*
 * The PWA manifest object, factored out of `vite.config.ts` (packet A5) so
 * `tests/unit/manifest.test.ts` can import and assert on it directly without
 * pulling in the whole Vite config (which loads the React/Tailwind/PWA
 * plugins and has a real side effect — see `vitest.config.ts`'s own
 * docstring for why the unit-test runner is deliberately not an extension of
 * `vite.config.ts`).
 *
 * `VitePWA({ manifest: buildManifest(mode) })` in `vite.config.ts` calls this
 * with the Vite build's own `mode` (see `defineConfig`'s function form
 * there); this file has no other Vite-specific code of its own — the
 * token/colour reads still just call `tokenHex`, the ordinary shared entry
 * point everything in `vite/` already uses for a manifest colour.
 *
 * ── The members below the original name/short_name/icons/theme_color set ────
 *
 * Added for the audit dossier's `manifest-*` findings (Id, Screenshots,
 * Orientation, manifest-dir, manifest-launch-handler, manifest-shortcuts,
 * manifest-categories, and the NOT-APPLICABLE-turned-PASS members —
 * display_override, edge_side_panel, handle_links, note_taking,
 * prefer_related_applications, protocol_handlers, scope_extensions,
 * widgets):
 *
 * - `id: "/"` — a stable install identity independent of `start_url`, so a
 *   later `start_url` change (a marketing query param, say) does not read as
 *   a different app to an OS that already has this one installed.
 * - `dir: "ltr"` — this product ships no RTL locale yet (see
 *   `rtlSafety.test.ts`'s own scope), so the manifest states the one
 *   direction it actually supports rather than leaving the field absent.
 * - `orientation: "any"` — a marking/study app has no portrait-only or
 *   landscape-only surface; locking orientation would fight a student who
 *   rotates to read a wide mark scheme.
 * - `prefer_related_applications: false` — there is no native app listed in
 *   `related_applications` for an OS to prefer instead.
 * - `display_override: ["standalone", "minimal-ui"]` — `display: "standalone"`
 *   stays the primary declaration (widest support); this is the fallback
 *   list newer UAs consult first, degrading to the same two modes rather
 *   than to a browser tab.
 * - `categories: ["education", "productivity"]` — both genuinely describe
 *   this product (past-paper marking and the study tools built on it), used
 *   by app-store-style listings and OS app search.
 * - `launch_handler: { client_mode: "navigate-existing" }` — re-opening an
 *   already-running installed instance focuses and navigates it rather than
 *   opening a second window, the same single-session assumption the rest of
 *   the app already makes about a signed-in student.
 * - `handle_links: "preferred"` — same-origin links open inside the
 *   installed app when it's running, rather than a second browser tab.
 * - `protocol_handlers` — registers `web+lemely://join/<code>` as this app's
 *   own URI scheme, resolving to `/join/<code>`. The `%s` placeholder is
 *   filled with the *whole* invoked URL, not just the trailing segment — see
 *   `src/lib/joinProtocol.ts`'s own docstring for why `/join/:code` has to
 *   parse both shapes.
 * - `edge_side_panel: { preferred_width: 400 }` — Edge's side-panel install
 *   surface; 400px comfortably fits this app's `max-w-100` (400px) auth/card
 *   column without introducing a second breakpoint.
 * - `scope_extensions` — associates the staging origin with this app's
 *   scope, so a staging link opened from an installed prod app still stays
 *   "inside" the app rather than escaping to a browser tab. **Gated to a
 *   staging build only** (A5 review fix): an installed *production* PWA
 *   must never treat `staging.lemelyig.com` navigations as trusted in-app
 *   content with no origin indicator, so `buildManifest`'s `mode` parameter
 *   — sourced from Vite's own build mode, `"production"` unless a build
 *   explicitly passes `--mode staging` — decides whether this member is
 *   present at all. `.github/workflows/deploy.yml`'s frontend build step
 *   passes `--mode ${{ needs.resolve-env.outputs.environment }}`, so the
 *   staging deploy job is the only one that ever produces a manifest
 *   carrying it.
 * - `note_taking: { new_note_url: "/student" }` — **not** `/student/practice`
 *   (A5 review fix): that path is not mounted (only `practice/:subjectCode`,
 *   `practice/set/:assignmentId` etc. are — `student/index.tsx`), and
 *   `student/data.ts`'s own comment already documents linking it as
 *   manufacturing a dead end. `/student`, the dashboard, is always mounted
 *   and is where a student would navigate to Practice from anyway.
 * - `shortcuts` — jump list / long-press entries for the three actions a
 *   returning student is most likely to want without opening the app first:
 *   marking a paper, the dashboard, and notifications.
 * - `screenshots` — generated by `scripts/manifest_screenshots.mjs`, never
 *   hand-typed (see that script's own header for why: real `sizes` off the
 *   actual saved JPEGs, not guessed).
 * - `widgets` — the Windows 11 / Android widget surface (`streak`), backed
 *   by `GET /api/student/widget` (`lemely/web/routers/widget.py`) and the
 *   Adaptive Card templates under `public/widgets/`.
 */

import { tokenHex } from "./brandTokens.ts"

/**
 * The PWA manifest, built for a given Vite `mode`.
 *
 * `mode` decides exactly one thing: whether `scope_extensions` is present —
 * see that member's own docstring paragraph, above, for why it must never
 * ship in a production build.
 */
export function buildManifest(mode: string) {
  return {
    name: "Lemely",
    short_name: "Lemely",
    description:
      "Lemely marks a student's photographed or uploaded past-paper attempt against the official marking scheme with method-mark awareness, returning per-question marks, grade, and weakness topics.",
    start_url: "/",
    id: "/",
    dir: "ltr" as const,
    display: "standalone" as const,
    orientation: "any" as const,
    // P6.5. These were `#1e1310` / `#faf4f2` under a comment claiming they
    // were computed from index.css via culori. Every clause of that comment
    // was false by the time it was read: `--ink` is `oklch(0.321 0.009
    // 234)` not `oklch(0.2 0.02 35)`, there is no `--bg` token, culori is
    // not a dependency of this project, and both hexes were build-era
    // Material-3 values that no token has produced since Phase 2 rewrote
    // the palette. Nothing failed, because an OS reads these and no test
    // does. Now computed at build time from the token file itself; see
    // web/vite/brandTokens.ts.
    //
    // Both are `--paper`. `theme_color` tints the app's own title bar and
    // `background_color` paints the splash screen shown before the first
    // frame renders, so making them the page colour means the launch reads
    // as the app appearing rather than as a flash of some other colour.
    theme_color: tokenHex("paper"),
    background_color: tokenHex("paper"),
    icons: [
      {
        src: "pwa-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "pwa-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "maskable-icon-512x512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    prefer_related_applications: false,
    display_override: ["standalone", "minimal-ui"] as ("standalone" | "minimal-ui")[],
    categories: ["education", "productivity"],
    launch_handler: { client_mode: "navigate-existing" as const },
    handle_links: "preferred" as const,
    protocol_handlers: [{ protocol: "web+lemely", url: "/join/%s" }],
    edge_side_panel: { preferred_width: 400 },
    // Staging-only — see this member's own docstring paragraph above.
    ...(mode === "staging" ? { scope_extensions: [{ origin: "https://staging.lemelyig.com" }] } : {}),
    note_taking: { new_note_url: "/student" },
    shortcuts: [
      {
        name: "Mark a paper",
        short_name: "Mark",
        url: "/student/correct",
        icons: [{ src: "shortcut-mark-96.png", sizes: "96x96", type: "image/png" }],
      },
      {
        name: "Dashboard",
        url: "/student",
        icons: [{ src: "shortcut-dashboard-96.png", sizes: "96x96", type: "image/png" }],
      },
      {
        name: "Notifications",
        url: "/student/notifications",
        icons: [{ src: "shortcut-notifications-96.png", sizes: "96x96", type: "image/png" }],
      },
    ],
    // Generated by `scripts/manifest_screenshots.mjs` — that script's stdout is
    // pasted here verbatim, never hand-typed (see its own header).
    screenshots: [
      {
        src: "screenshots/dashboard-wide.jpg",
        sizes: "2880x1800",
        type: "image/jpeg",
        form_factor: "wide" as const,
        label:
          "The student dashboard: subjects this session with predicted grades, a momentum chart, and weakest topics.",
      },
      {
        src: "screenshots/dashboard-narrow.jpg",
        sizes: "780x1688",
        type: "image/jpeg",
        form_factor: "narrow" as const,
        label: "The student dashboard on a phone: subjects this session and predicted grades.",
      },
    ],
    widgets: [
      {
        name: "Streak",
        tag: "lemely-streak",
        ms_ac_template: "widgets/streak.json",
        data: "widgets/streak-data.json",
        description: "Your study streak and next session",
        screenshots: [
          { src: "screenshots/dashboard-narrow.jpg", sizes: "780x1688", label: "Streak widget preview" },
        ],
      },
    ],
    // Web Share Target: lets a student share a photo straight out of the OS
    // camera roll or another app into Lemely instead of opening the app first
    // and picking a file. `src/sw/shareTarget.ts`'s `handleShareTargetFetch`
    // is the `/share-target` handler this POST actually reaches; the `scan`
    // field name here and the `formData.get("scan")` read there have to
    // agree, since nothing else pins that string to both places.
    share_target: {
      action: "/share-target",
      method: "POST" as const,
      enctype: "multipart/form-data",
      params: {
        files: [{ name: "scan", accept: ["image/*", "application/pdf"] }],
      },
    },
    // File Handling API: the OS "open with Lemely" counterpart to
    // share_target above, for the same two scan formats. `/file-handler`
    // (routes.tsx) redirects into the same marking flow; `launchQueue` in
    // `CorrectPaper.tsx` is what actually receives the launched file.
    file_handlers: [
      {
        action: "/file-handler",
        accept: {
          "image/*": [".png", ".jpg", ".jpeg"],
          "application/pdf": [".pdf"],
        },
      },
    ],
  }
}
