"""Versioned prompts for AI study-plan narration."""

from __future__ import annotations

import json

from lemely.core.study import StudyPlan

VERSION = "1"


def build_study_plan_system_prompt() -> str:
    return (
        "You are an experienced Cambridge IGCSE tutor and study coach. "
        "You have been given a structured study plan generated by an algorithm. "
        "Your job is to enrich it with a clear, motivating, and actionable narrative "
        "that a student can follow. Keep the same sessions, activity types, "
        "durations, and topics — only populate the 'narrative' field with your "
        "guidance. "
        "Be specific, practical, and encouraging. "
        "Return ONLY valid JSON matching the StudyPlan schema exactly."
    )


def build_study_plan_user_prompt(plan: StudyPlan) -> str:
    plan_json = json.dumps(plan.model_dump(mode="json"), indent=2)
    return (
        f"Here is the algorithmic study plan for student '{plan.student_id}':\n\n"
        f"{plan_json}\n\n"
        "Please populate the 'narrative' field with a 2-3 paragraph study guide. "
        "Keep all other fields identical to the input. Return the complete StudyPlan JSON."
    )
