"""core schema

Revision ID: 0002_core_schema
Revises: 0001_baseline
Create Date: 2026-07-30 11:51:51.040524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_core_schema'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_minor', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.String(), server_default=sa.text("'EGP'"), nullable=False),
    sa.Column('interval', sa.Enum('monthly', 'yearly', name='planinterval'), nullable=True),
    sa.Column('max_devices', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_tiers')),
    sa.UniqueConstraint('code', name=op.f('uq_plan_tiers_code'))
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('board', sa.Enum('caie', 'edexcel', 'oxford_aqa', name='examboard'), server_default=sa.text("'caie'::examboard"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('student', 'parent', 'teacher', 'school_admin', 'platform_admin', name='role'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('locale', sa.String(), server_default=sa.text("'en'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_label', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('refresh_token_id', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index('ix_devices_user_id_revoked_at', 'devices', ['user_id', 'revoked_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('grade_ready', 'announcement', 'streak_warning', 'study_plan_reminder', 'at_risk_alert', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_read_at', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('board', sa.Enum('caie', 'edexcel', 'oxford_aqa', name='examboard'), server_default=sa.text("'caie'::examboard"), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('session_month', sa.Enum('may_june', 'oct_nov', 'feb_mar', 'specimen', name='sessionmonth'), nullable=False),
    sa.Column('session_year', sa.Integer(), nullable=True),
    sa.Column('paper_number', sa.Integer(), nullable=False),
    sa.Column('paper_variant', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.code'], name=op.f('fk_papers_subject_code_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_papers')),
    sa.UniqueConstraint('board', 'subject_code', 'session_month', 'session_year', 'paper_number', 'paper_variant', name='uq_papers_identity')
    )
    op.create_index('ix_papers_board_subject_code_session', 'papers', ['board', 'subject_code', 'session_month', 'session_year', 'paper_number', 'paper_variant'], unique=False)
    op.create_table('parent_child_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], name=op.f('fk_parent_child_links_child_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_child_links_parent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_child_links')),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_parent_child_links_parent_id_child_id')
    )
    op.create_table('schools',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seat_quota', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_schools_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('streaks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_length', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('longest_length', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_active_on', sa.Date(), nullable=True),
    sa.Column('freezes_available', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_streaks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streaks')),
    sa.UniqueConstraint('user_id', name=op.f('uq_streaks_user_id'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_tier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('inactive', 'active', 'cancelled', 'expired', name='subscriptionstatus'), server_default=sa.text("'inactive'::subscriptionstatus"), nullable=False),
    sa.Column('is_manually_activated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_tier_id'], ['plan_tiers.id'], name=op.f('fk_subscriptions_plan_tier_id_plan_tiers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index('ix_subscriptions_user_id_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='uploadstatus'), server_default=sa.text("'pending'::uploadstatus"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_uploads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_table('xp_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('paper_corrected', 'quiz_completed', 'flashcard_reviewed', 'study_session_completed', name='xpsource'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('awarded_on', sa.Date(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_events'))
    )
    op.create_index('ix_xp_events_user_id_awarded_on', 'xp_events', ['user_id', 'awarded_on'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.Column('paper_id', sa.UUID(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('session_month', sa.Enum('may_june', 'oct_nov', 'feb_mar', 'specimen', name='sessionmonth'), nullable=True),
    sa.Column('session_year', sa.Integer(), nullable=True),
    sa.Column('paper_number', sa.Integer(), nullable=True),
    sa.Column('paper_variant', sa.Integer(), nullable=True),
    sa.Column('awarded_marks', sa.Integer(), nullable=False),
    sa.Column('maximum_marks', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('predicted_grade', sa.String(), nullable=True),
    sa.Column('boundary_source', sa.Enum('exact', 'subject_default', 'global_default', name='boundarysource'), nullable=True),
    sa.Column('confidence_band', sa.Enum('high', 'medium', 'low', name='confidenceband'), nullable=True),
    sa.Column('needs_teacher_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_attempts_paper_id_papers')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_attempts_upload_id_uploads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index('ix_attempts_user_id_recorded_at', 'attempts', ['user_id', 'recorded_at'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_classes_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_table('mark_schemes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('maximum_mark', sa.Integer(), nullable=False),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('parsed_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name=op.f('fk_mark_schemes_paper_id_papers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mark_schemes')),
    sa.UniqueConstraint('paper_id', name=op.f('uq_mark_schemes_paper_id'))
    )
    op.create_table('school_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('membership_role', sa.Enum('teacher', 'school_admin', name='membershiprole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_memberships_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_school_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_memberships')),
    sa.UniqueConstraint('school_id', 'user_id', name='uq_school_memberships_school_id_user_id')
    )
    op.create_table('seats',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'revoked', name='seatstatus'), server_default=sa.text("'available'::seatstatus"), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_seats_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_seats_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats'))
    )
    op.create_index('ix_seats_school_id_status', 'seats', ['school_id', 'status'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_announcements_author_id_users')),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_announcements_class_id_classes')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_announcements_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('class_enrollments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_enrollments_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_class_enrollments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_enrollments')),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_class_enrollments_class_id_student_id')
    )
    op.create_table('question_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('awarded_marks', sa.Integer(), nullable=False),
    sa.Column('maximum_marks', sa.Integer(), nullable=False),
    sa.Column('confidence_band', sa.Enum('high', 'medium', 'low', name='confidenceband'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('needs_teacher_review', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('marker_source', sa.Enum('deterministic', 'ai', 'missing', name='markersource'), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('matched_point_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_question_results_attempt_id_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_results'))
    )
    op.create_index('ix_question_results_attempt_id', 'question_results', ['attempt_id'], unique=False)
    op.create_table('weakness_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('lost_marks', sa.Integer(), nullable=False),
    sa.Column('maximum_marks', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('question_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_weakness_records_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weakness_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weakness_records'))
    )
    op.create_index('ix_weakness_records_user_id_topic', 'weakness_records', ['user_id', 'topic'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_result_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('low_confidence', 'plagiarism_flag', 'ai_detection_flag', 'manual', name='reviewreason'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='reviewstatus'), server_default=sa.text("'open'::reviewstatus"), nullable=False),
    sa.Column('assigned_teacher_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_teacher_id'], ['users.id'], name=op.f('fk_review_queue_assigned_teacher_id_users')),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_review_queue_attempt_id_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_result_id'], ['question_results.id'], name=op.f('fk_review_queue_question_result_id_question_results')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_review_queue_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    op.create_index('ix_review_queue_status', 'review_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index('ix_weakness_records_user_id_topic', table_name='weakness_records')
    op.drop_table('weakness_records')
    op.drop_index('ix_question_results_attempt_id', table_name='question_results')
    op.drop_table('question_results')
    op.drop_table('class_enrollments')
    op.drop_table('announcements')
    op.drop_index('ix_seats_school_id_status', table_name='seats')
    op.drop_table('seats')
    op.drop_table('school_memberships')
    op.drop_table('mark_schemes')
    op.drop_table('classes')
    op.drop_index('ix_attempts_user_id_recorded_at', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('ix_xp_events_user_id_awarded_on', table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_table('uploads')
    op.drop_index('ix_subscriptions_user_id_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('streaks')
    op.drop_table('schools')
    op.drop_table('parent_child_links')
    op.drop_index('ix_papers_board_subject_code_session', table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_notifications_user_id_read_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_devices_user_id_revoked_at', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('plan_tiers')
    # Drop all ENUM types explicitly (autogenerate omits these in downgrade).
    op.execute('DROP TYPE IF EXISTS reviewstatus')
    op.execute('DROP TYPE IF EXISTS reviewreason')
    op.execute('DROP TYPE IF EXISTS notificationtype')
    op.execute('DROP TYPE IF EXISTS xpsource')
    op.execute('DROP TYPE IF EXISTS uploadstatus')
    op.execute('DROP TYPE IF EXISTS boundarysource')
    op.execute('DROP TYPE IF EXISTS confidenceband')
    op.execute('DROP TYPE IF EXISTS markersource')
    op.execute('DROP TYPE IF EXISTS sessionmonth')
    op.execute('DROP TYPE IF EXISTS seatstatus')
    op.execute('DROP TYPE IF EXISTS membershiprole')
    op.execute('DROP TYPE IF EXISTS subscriptionstatus')
    op.execute('DROP TYPE IF EXISTS planinterval')
    op.execute('DROP TYPE IF EXISTS examboard')
    op.execute('DROP TYPE IF EXISTS role')
    # ### end Alembic commands ###
