"""quiz model: question bank, quizzes, assignments, submissions, answers

Revision ID: 0007_quiz_model
Revises: 0006_at_risk_acknowledgements
Create Date: 2026-08-06 00:00:00.000000

P3.5 chunk A / ``docs/quiz-model.md`` §1. Schema only — no repo, service, or
route reads or writes any of this yet. Additive throughout (D1.2/D1.3): six
new tables plus one additive, defaulted column on ``attempts``. Nothing
existing is dropped, renamed, or repurposed.

* ``attempts.origin`` (§1.2) — what kind of assessment produced an attempt.
  ``NOT NULL DEFAULT 'past_paper'``, so every existing row is correctly
  classified with no backfill.
* ``question_bank`` (§1.3) — the queryable question pool. Partial unique
  index ``uq_question_bank_paper_question`` (``WHERE paper_id IS NOT NULL``)
  makes the chunk-B past-paper ingest idempotent.
* ``quizzes`` (§1.4) — a teacher-built quiz, draft through archived.
* ``quiz_questions`` (§1.5) — the curated, ordered, materialized question
  set a quiz contains; question text is copied from ``question_bank``, not
  referenced, so a quiz's assessment record cannot change after the fact.
* ``quiz_assignments`` (§1.6) — a quiz handed to a class.
* ``quiz_submissions`` (§1.7) — one student's attempt at an assignment.
* ``quiz_answers`` (§1.8) — what a student actually wrote, independent of
  any marking run.

**Enum type creation — the usual Alembic/Postgres failure mode, handled
explicitly.** Unlike ``0002_core_schema`` (a single autogenerated baseline
where every enum-bearing table is created in one pass and SQLAlchemy's
``Table.create()`` DDL sequence auto-creates each enum type as a side
effect), ``op.create_table`` here runs with ``checkfirst=False`` and will
try to ``CREATE TYPE`` again for any enum reused across statements — which
fails with ``DuplicateObject`` for a type that already exists (``examboard``,
created by ``0002``) or for a brand-new type referenced by more than one
table below (``questionsource`` on both ``question_bank`` and ``quizzes``;
``questiondifficulty`` on both ``question_bank`` and ``quiz_questions``).
``attemptorigin`` has the same problem in a different shape: ``op.add_column``
on an *existing* table never triggers the table-create DDL sequence at all,
so the type is never auto-created there either.

The fix applied uniformly below: every new enum type is created exactly
once, explicitly, up front (``checkfirst=True`` so a partial prior run is
never fatal), and every column reference uses ``postgresql.ENUM(...,
create_type=False)`` so SQLAlchemy never attempts to recreate a type that is
already known to exist. ``examboard`` (pre-existing) gets the same
``create_type=False`` treatment with no creation call, since ``0002`` already
made it. All eight types touched here (`attemptorigin` plus the seven new
ones) are dropped explicitly in ``downgrade()`` after every table that
references them is gone — autogenerate omits explicit type drops, the same
gap ``0002_core_schema`` and ``0006_at_risk_acknowledgements`` fill by hand.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007_quiz_model"
down_revision: Union[str, Sequence[str], None] = "0006_at_risk_acknowledgements"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # --- enum types: created exactly once, explicitly, before any column
    # references them (see module docstring for why this cannot be left to
    # SQLAlchemy's create_table auto-creation here). -------------------------
    attempt_origin = postgresql.ENUM(
        "past_paper", "quiz", "custom_paper", name="attemptorigin"
    )
    question_source = postgresql.ENUM(
        "past_paper", "generated", "teacher_upload", name="questionsource"
    )
    question_difficulty = postgresql.ENUM(
        "foundation", "standard", "challenge", name="questiondifficulty"
    )
    difficulty_source = postgresql.ENUM(
        "declared_by_generator",
        "inferred_from_marks",
        "teacher_set",
        name="difficultysource",
    )
    quiz_status = postgresql.ENUM("draft", "assigned", "closed", "archived", name="quizstatus")
    quiz_question_status = postgresql.ENUM("included", "removed", name="quizquestionstatus")
    quiz_submission_status = postgresql.ENUM(
        "not_started", "in_progress", "submitted", "marked", name="quizsubmissionstatus"
    )
    for enum_type in (
        attempt_origin,
        question_source,
        question_difficulty,
        difficulty_source,
        quiz_status,
        quiz_question_status,
        quiz_submission_status,
    ):
        enum_type.create(bind, checkfirst=True)

    # examboard already exists (0002_core_schema); reused here read-only.
    exam_board = postgresql.ENUM(
        "caie", "edexcel", "oxford_aqa", name="examboard", create_type=False
    )

    # --- attempts.origin -----------------------------------------------
    op.add_column(
        "attempts",
        sa.Column(
            "origin",
            postgresql.ENUM(
                "past_paper", "quiz", "custom_paper", name="attemptorigin", create_type=False
            ),
            server_default=sa.text("'past_paper'::attemptorigin"),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_attempts_user_id_origin", "attempts", ["user_id", "origin"], unique=False
    )

    # --- question_bank -------------------------------------------------
    op.create_table(
        "question_bank",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "board", exam_board, server_default=sa.text("'caie'::examboard"), nullable=False
        ),
        sa.Column("subject_code", sa.String(), nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM(
                "past_paper",
                "generated",
                "teacher_upload",
                name="questionsource",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("paper_id", sa.UUID(), nullable=True),
        sa.Column("source_question_id", sa.String(), nullable=True),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column(
            "difficulty",
            postgresql.ENUM(
                "foundation",
                "standard",
                "challenge",
                name="questiondifficulty",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty_source",
            postgresql.ENUM(
                "declared_by_generator",
                "inferred_from_marks",
                "teacher_set",
                name="difficultysource",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("question_type", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model_answer", sa.Text(), nullable=True),
        sa.Column(
            "mark_scheme_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("mcq_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mcq_answer", sa.String(), nullable=True),
        sa.Column("total_marks", sa.Integer(), nullable=False),
        sa.Column(
            "source_question_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_question_bank_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_question_bank_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"], ["papers.id"], name=op.f("fk_question_bank_paper_id_papers")
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_question_bank_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_bank")),
    )
    op.create_index(
        "ix_question_bank_pool",
        "question_bank",
        ["subject_code", "source", "difficulty", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_question_bank_topic",
        "question_bank",
        ["subject_code", "topic", "is_active"],
        unique=False,
    )
    op.create_index("ix_question_bank_owner", "question_bank", ["owner_id"], unique=False)
    op.create_index(
        "uq_question_bank_paper_question",
        "question_bank",
        ["paper_id", "source_question_id"],
        unique=True,
        postgresql_where=sa.text("paper_id IS NOT NULL"),
    )

    # --- quizzes ---------------------------------------------------------
    op.create_table(
        "quizzes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("subject_code", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "draft", "assigned", "closed", "archived", name="quizstatus", create_type=False
            ),
            server_default=sa.text("'draft'::quizstatus"),
            nullable=False,
        ),
        sa.Column("target_grade", sa.String(), nullable=True),
        sa.Column(
            "included_topics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "pool_source",
            postgresql.ENUM(
                "past_paper",
                "generated",
                "teacher_upload",
                name="questionsource",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("requested_count", sa.Integer(), nullable=True),
        sa.Column("time_limit_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "builder_step", sa.SmallInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_quizzes_school_id_schools"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_quizzes_teacher_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
    )
    op.create_index(
        "ix_quizzes_teacher_status", "quizzes", ["teacher_id", "status"], unique=False
    )

    # --- quiz_questions ----------------------------------------------------
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("question_bank_id", sa.UUID(), nullable=True),
        sa.Column("question_ref", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "included", "removed", name="quizquestionstatus", create_type=False
            ),
            server_default=sa.text("'included'::quizquestionstatus"),
            nullable=False,
        ),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("topic", sa.String(), nullable=True),
        sa.Column(
            "difficulty",
            postgresql.ENUM(
                "foundation",
                "standard",
                "challenge",
                name="questiondifficulty",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("question_type", sa.String(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("model_answer", sa.Text(), nullable=True),
        sa.Column(
            "mark_scheme_points",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("mcq_options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mcq_answer", sa.String(), nullable=True),
        sa.Column("total_marks", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["question_bank_id"],
            ["question_bank.id"],
            name=op.f("fk_quiz_questions_question_bank_id_question_bank"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_questions_replaced_by_id_quiz_questions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
    )
    op.create_index(
        "uq_quiz_questions_ref", "quiz_questions", ["quiz_id", "question_ref"], unique=True
    )
    op.create_index(
        "ix_quiz_questions_quiz_position",
        "quiz_questions",
        ["quiz_id", "position", "status"],
        unique=False,
    )

    # --- quiz_assignments ----------------------------------------------------
    op.create_table(
        "quiz_assignments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("class_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"], ["users.id"], name=op.f("fk_quiz_assignments_assigned_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_quiz_assignments_class_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_assignments_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_assignments")),
    )
    op.create_index(
        "uq_quiz_assignments", "quiz_assignments", ["quiz_id", "class_id"], unique=True
    )
    op.create_index(
        "ix_quiz_assignments_class",
        "quiz_assignments",
        ["class_id", "assigned_at"],
        unique=False,
    )

    # --- quiz_submissions ----------------------------------------------------
    op.create_table(
        "quiz_submissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("assignment_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "not_started",
                "in_progress",
                "submitted",
                "marked",
                name="quizsubmissionstatus",
                create_type=False,
            ),
            server_default=sa.text("'not_started'::quizsubmissionstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("marked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_id", sa.UUID(), nullable=True),
        sa.Column("marking_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["quiz_assignments.id"],
            name=op.f("fk_quiz_submissions_assignment_id_quiz_assignments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_quiz_submissions_attempt_id_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f("fk_quiz_submissions_student_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_submissions")),
    )
    op.create_index(
        "uq_quiz_submissions", "quiz_submissions", ["assignment_id", "student_id"], unique=True
    )
    op.create_index(
        "ix_quiz_submissions_status",
        "quiz_submissions",
        ["assignment_id", "status"],
        unique=False,
    )

    # --- quiz_answers ----------------------------------------------------
    op.create_table(
        "quiz_answers",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("quiz_question_id", sa.UUID(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=True),
        sa.Column("working_text", sa.Text(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quiz_question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_answers_quiz_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["quiz_submissions.id"],
            name=op.f("fk_quiz_answers_submission_id_quiz_submissions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_answers")),
    )
    op.create_index(
        "uq_quiz_answers", "quiz_answers", ["submission_id", "quiz_question_id"], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("uq_quiz_answers", table_name="quiz_answers")
    op.drop_table("quiz_answers")

    op.drop_index("ix_quiz_submissions_status", table_name="quiz_submissions")
    op.drop_index("uq_quiz_submissions", table_name="quiz_submissions")
    op.drop_table("quiz_submissions")

    op.drop_index("ix_quiz_assignments_class", table_name="quiz_assignments")
    op.drop_index("uq_quiz_assignments", table_name="quiz_assignments")
    op.drop_table("quiz_assignments")

    op.drop_index("ix_quiz_questions_quiz_position", table_name="quiz_questions")
    op.drop_index("uq_quiz_questions_ref", table_name="quiz_questions")
    op.drop_table("quiz_questions")

    op.drop_index("ix_quizzes_teacher_status", table_name="quizzes")
    op.drop_table("quizzes")

    op.drop_index("uq_question_bank_paper_question", table_name="question_bank")
    op.drop_index("ix_question_bank_owner", table_name="question_bank")
    op.drop_index("ix_question_bank_topic", table_name="question_bank")
    op.drop_index("ix_question_bank_pool", table_name="question_bank")
    op.drop_table("question_bank")

    op.drop_index("ix_attempts_user_id_origin", table_name="attempts")
    op.drop_column("attempts", "origin")

    # Drop all ENUM types explicitly (autogenerate omits these in downgrade;
    # see 0002_core_schema and 0006_at_risk_acknowledgements). examboard is
    # NOT dropped here — it is owned by 0002, not by this migration.
    bind = op.get_bind()
    for type_name in (
        "quizsubmissionstatus",
        "quizquestionstatus",
        "quizstatus",
        "difficultysource",
        "questiondifficulty",
        "questionsource",
        "attemptorigin",
    ):
        postgresql.ENUM(name=type_name).drop(bind, checkfirst=True)
