"""reference catalogue: syllabus papers and subject topics

Revision ID: 0024_reference_catalogue
Revises: 0023_invites
Create Date: 2026-09-02 00:00:00.000000

Two additive tables plus three columns on ``subjects``, and the data that used
to live in ``lemely/data/paper_timing.json`` and
``lemely/data/syllabus_topics.json``. Those files are deleted in the same
change, which is why the rows are **embedded here as literals** rather than
read from disk at migration time: a migration that reads a file the repository
no longer contains cannot be replayed on a fresh database, and replayability is
the whole contract of a migration.

``papertier`` is a new enum. It is nullable on ``syllabus_papers`` because not
every syllabus is tiered — 0606 has no Core/Extended split, and inventing one
would be a claim the syllabus does not make.

``subjects.active`` exists because ``papers.subject_code`` is a foreign key to
``subjects.code``: ingesting a fourth subject's past papers would otherwise
enrol students in it through onboarding as a side effect.

Reversible: ``downgrade`` drops both tables, drops the three added columns, then
drops the ``papertier`` type explicitly — a table drop does not drop the type
backing an enum column, the trap ``0006`` and ``0022`` both document.
"""

from __future__ import annotations

import json as _json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
# Kept to <=32 chars: alembic_version.version_num is varchar(32).
revision: str = "0024_reference_catalogue"
down_revision: str | Sequence[str] | None = "0023_invites"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ---------------------------------------------------------------------------
# Row literals, transcribed from lemely/data/paper_timing.json and
# lemely/data/syllabus_topics.json as they stood at the time of this
# migration. Generated by the repo's Task-2 literal-generator script; not
# hand-typed, and not re-read from disk at migration time (see module
# docstring).
# ---------------------------------------------------------------------------

PAPERS = [
    dict(board='caie', subject_code='0625', paper_number=1, name='Multiple Choice (Core)', tier='core', duration_minutes=45, total_marks=40, practical=False, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0625', paper_number=2, name='Multiple Choice (Extended)', tier='extended', duration_minutes=45, total_marks=40, practical=False, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0625', paper_number=3, name='Theory (Core)', tier='core', duration_minutes=75, total_marks=80, practical=False, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0625', paper_number=4, name='Theory (Extended)', tier='extended', duration_minutes=75, total_marks=80, practical=False, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0625', paper_number=5, name='Practical Test', tier=None, duration_minutes=75, total_marks=40, practical=True, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0625', paper_number=6, name='Alternative to Practical', tier=None, duration_minutes=60, total_marks=40, practical=True, source_document='595430-2023-2025-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf', syllabus_version='2023-2025'),
    dict(board='caie', subject_code='0580', paper_number=1, name='Non-calculator (Core)', tier='core', duration_minutes=90, total_marks=80, practical=False, source_document='662466-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662466-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
    dict(board='caie', subject_code='0580', paper_number=2, name='Non-calculator (Extended)', tier='extended', duration_minutes=120, total_marks=100, practical=False, source_document='662466-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662466-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
    dict(board='caie', subject_code='0580', paper_number=3, name='Calculator (Core)', tier='core', duration_minutes=90, total_marks=80, practical=False, source_document='662466-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662466-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
    dict(board='caie', subject_code='0580', paper_number=4, name='Calculator (Extended)', tier='extended', duration_minutes=120, total_marks=100, practical=False, source_document='662466-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662466-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
    dict(board='caie', subject_code='0606', paper_number=1, name='Non-calculator', tier=None, duration_minutes=120, total_marks=80, practical=False, source_document='662470-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662470-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
    dict(board='caie', subject_code='0606', paper_number=2, name='Calculator', tier=None, duration_minutes=120, total_marks=80, practical=False, source_document='662470-2025-2027-syllabus.pdf', source_url='https://www.cambridgeinternational.org/Images/662470-2025-2027-syllabus.pdf', syllabus_version='2025-2027'),
]
SUBJECTS = [
    dict(code='0625', name='Physics', syllabus_version='2023-2025', source_url='https://www.cambridgeinternational.org/Images/595430-2023-2025-syllabus.pdf'),
    dict(code='0580', name='Mathematics', syllabus_version='2025-2027', source_url='https://www.cambridgeinternational.org/Images/662466-2025-2027-syllabus.pdf'),
    dict(code='0606', name='Additional Mathematics', syllabus_version='2025-2027', source_url='https://www.cambridgeinternational.org/Images/662470-2025-2027-syllabus.pdf'),
]
TOPICS = {
    '0625': [
        ('1', 'Motion, forces and energy', None, [], ['force', 'motion', 'energy']),
        ('1.1', 'Physical quantities and measurement techniques', '1', ['measuring cylinder', 'micrometer', 'vernier', 'scalar quantity', 'vector quantity', 'line of sight', 'parallax', 'scalars', 'vectors'], ['ruler', 'measuring', 'stopwatch', 'pendulum', 'average value', 'magnitude and direction', 'significant figures', 'measurement']),
        ('1.2', 'Motion', '1', ['speed-time', 'distance-time', 'deceleration', 'terminal velocity', 'acceleration of free fall', 'average speed'], ['speed', 'velocity', 'acceleration', 'area under the graph', 'gradient of the graph', 'distance travelled', 'm/s']),
        ('1.3', 'Mass and weight', '1', ['gravitational field strength', 'mass and weight', 'n/kg', 'weight of the', 'calculate the weight', 'unit of weight'], ['weight', 'beam balance', 'quantity of matter', 'weighs']),
        ('1.4', 'Density', '1', ['density', 'g/cm3', 'kg/m3', 'mass per unit volume', 'floats', 'displacement can'], ['volume', 'irregular solid', 'sinks']),
        ('1.5', 'Forces', '1', ['resultant force', 'hooke', 'spring constant', 'limit of proportionality', 'friction', 'air resistance', 'drag', 'centre of gravity', 'moment of a force', 'principle of moments', 'circular motion', 'extension', 'load-extension'], ['force', 'newton', 'equilibrium', 'pivot', 'balanced', 'turning effect', 'free-body', "newton's"]),
        ('1.6', 'Momentum', '1', ['momentum', 'impulse', 'conservation of momentum', 'kg m/s'], ['collision', 'collide', 'rate of change of momentum']),
        ('1.7', 'Energy, work and power', '1', ['kinetic energy', 'gravitational potential energy', 'efficiency', 'work done', 'power', 'conservation of energy', 'fossil fuel', 'geothermal', 'photovoltaic', 'wind turbine', 'hydroelectric', 'biofuel', 'energy resource'], ['energy', 'joule', 'watt', 'transferred', 'energy store', 'useful output', 'chemical energy', 'internal energy']),
        ('1.8', 'Pressure', '1', ['pressure', 'pascal', 'manometer', 'barometer', 'hydraulic', 'force per unit area', 'n/m2'], ['atmospheric', 'depth', 'liquid column', 'area of contact']),
        ('2', 'Thermal physics', None, [], ['thermal', 'temperature', 'heat']),
        ('2.1', 'Kinetic particle model of matter', '2', ['kinetic particle model', 'brownian motion', 'evaporation', 'absolute zero', 'kelvin', 'gas pressure', 'boyle', 'fixed mass of gas', 'constant volume', 'constant temperature'], ['solid', 'liquid', 'gas', 'molecule', 'particle', 'condensation', 'melting', 'boiling', 'random motion', 'change of state', 'sublimation']),
        ('2.2', 'Thermal properties and temperature', '2', ['specific heat capacity', 'specific latent heat', 'latent heat of fusion', 'latent heat of vaporisation', 'thermal expansion', 'thermocouple', 'liquid-in-glass thermometer', 'bimetallic'], ['thermometer', 'expands', 'expansion', 'melting point', 'boiling point', 'thermal capacity', 'heating curve']),
        ('2.3', 'Transfer of thermal energy', '2', ['conduction', 'convection', 'thermal radiation', 'infrared radiation', 'convection current', 'dull black', 'shiny', 'emitter of infrared'], ['thermal energy', 'conductor', 'insulator', 'radiation', 'absorb', 'emit', 'vacuum flask', 'lagging']),
        ('3', 'Waves', None, [], ['wave']),
        ('3.1', 'General properties of waves', '3', ['wavefront', 'transverse wave', 'longitudinal wave', 'ripple tank', 'diffraction', 'wave speed', 'wave equation'], ['wavelength', 'frequency', 'amplitude', 'crest', 'trough', 'compression', 'rarefaction', 'hertz', 'wave']),
        ('3.2', 'Light', '3', ['refractive index', 'critical angle', 'total internal reflection', 'converging lens', 'diverging lens', 'focal length', 'principal focus', 'angle of incidence', 'angle of refraction', 'angle of reflection', 'plane mirror', 'ray diagram', 'dispersion', 'prism', 'real image', 'virtual image', 'magnifying glass', 'optical fibre', 'the normal', 'angle to the normal'], ['light', 'reflection', 'refraction', 'lens', 'image', 'ray', 'spectrum of colours']),
        ('3.3', 'Electromagnetic spectrum', '3', ['electromagnetic spectrum', 'gamma rays', 'x-rays', 'ultraviolet', 'microwaves', 'radio waves', 'analogue signal', 'digital signal', 'electromagnetic waves'], ['speed of light', 'transmission', 'wireless', 'satellite']),
        ('3.4', 'Sound', '3', ['ultrasound', 'echo', 'pitch', 'loudness', 'sound wave', 'audible range', '20 000 hz'], ['sound', 'vibrating', 'medium', 'travels through', 'reflection of sound']),
        ('4', 'Electricity and magnetism', None, [], ['electric', 'magnetic']),
        ('4.1', 'Simple phenomena of magnetism', '4', ['magnetic field line', 'induced magnetism', 'permanent magnet', 'soft iron', 'magnetise', 'demagnetise', 'plotting compass', 'north pole', 'south pole'], ['magnet', 'magnetic', 'attract', 'repel', 'steel']),
        ('4.2', 'Electrical quantities', '4', ['electric charge', 'coulomb', 'electromotive force', 'e.m.f.', 'potential difference', 'resistance', 'ammeter', 'voltmeter', 'electrostatic', 'electric field', 'resistivity', 'kilowatt-hour', 'ohm'], ['current', 'charge', 'volt', 'ampere', 'electron', 'p.d.', 'electrical power', 'electrical energy', 'conductor', 'insulator']),
        ('4.3', 'Electric circuits', '4', ['in series', 'in parallel', 'circuit diagram', 'combined resistance', 'potential divider', 'thermistor', 'light-dependent resistor', 'variable resistor', 'rheostat', 'diode', 'relay', 'ldr'], ['circuit', 'component', 'lamp', 'battery', 'cell', 'switch', 'resistor', 'junction']),
        ('4.4', 'Electrical safety', '4', ['live wire', 'neutral wire', 'earth wire', 'fuse', 'circuit breaker', 'trip switch', 'double insulated', 'mains circuit', 'mains supply'], ['hazard', 'safety', 'damaged insulation', 'overheating', 'socket', 'electric shock']),
        ('4.5', 'Electromagnetic effects', '4', ['electromagnetic induction', 'transformer', 'd.c. motor', 'a.c. generator', 'solenoid', 'step-up', 'step-down', 'split-ring commutator', 'slip ring', 'induced e.m.f.', 'high-voltage transmission', 'left-hand rule', 'right-hand', 'loudspeaker', 'high voltage'], ['coil', 'number of turns', 'magnetic effect of a current', 'current-carrying', 'electromagnet', 'dynamo', 'alternating current']),
        ('5', 'Nuclear physics', None, [], ['nuclear', 'nucleus']),
        ('5.1', 'The nuclear model of the atom', '5', ['nucleon number', 'proton number', 'nuclide notation', 'isotope', 'alpha-particle scattering', 'nuclear fission', 'nuclear fusion', 'quark'], ['nucleus', 'proton', 'neutron', 'electron', 'atom', 'ion', 'atomic']),
        ('5.2', 'Radioactivity', '5', ['background radiation', 'half-life', 'alpha-particle', 'beta-particle', 'gamma-ray', 'radioactive decay', 'ionising', 'decay equation', 'count rate', 'geiger', 'radioactive isotope', 'radioactive source'], ['radiation', 'radioactive', 'emitted', 'random', 'absorbed by', 'detector']),
        ('6', 'Space physics', None, [], ['space']),
        ('6.1', 'Earth and the Solar System', '6', ['solar system', 'asteroid', 'comet', 'elliptical orbit', 'orbital speed', 'phases of the moon', 'the sun contains', 'rocky planet', 'gas giant'], ['earth', 'planet', 'orbit', 'rotates', 'axis', 'moon', 'sun', 'day', 'year', 'gravitational attraction']),
        ('6.2', 'Stars and the Universe', '6', ['milky way', 'galaxy', 'galaxies', 'red giant', 'white dwarf', 'supernova', 'neutron star', 'black hole', 'nebula', 'redshift', 'cosmic microwave background', 'hubble constant', 'big bang', 'light-year', 'main sequence', 'protostar', 'planetary nebula', 'the universe', 'life cycle of a star', 'life cycle of stars'], ['star', 'universe', 'expanding', 'stable star', 'hydrogen and helium']),
    ],
    '0580': [
        ('1', 'Number', None, [], ['number']),
        ('1.1', 'Types of number', '1', ['prime number', 'square number', 'cube number', 'highest common factor', 'lowest common multiple', 'rational number', 'irrational number', 'reciprocal'], ['integer', 'factor', 'multiple', 'even', 'odd']),
        ('1.2', 'Sets', '1', ['venn diagram', 'universal set', 'intersection', 'complement of', 'subset', 'set notation'], ['element of', 'union', 'n(a)']),
        ('1.3', 'Powers and roots', '1', ['square root', 'cube root', 'power of'], ['squared', 'cubed', 'root']),
        ('1.4', 'Fractions, decimals and percentages', '1', ['recurring decimal', 'improper fraction', 'mixed number', 'equivalent fraction'], ['fraction', 'decimal', 'percentage', 'numerator', 'denominator']),
        ('1.5', 'Ordering', '1', ['ascending order', 'descending order', 'in order of size'], ['greater than', 'less than', 'order']),
        ('1.6', 'The four operations', '1', ['order of operations', 'bidmas', 'brackets first'], ['add', 'subtract', 'multiply', 'divide', 'negative number']),
        ('1.7', 'Indices I', '1', ['index notation', 'laws of indices'], ['index', 'indices', 'power']),
        ('1.8', 'Standard form', '1', ['standard form'], ['× 10', '10n']),
        ('1.9', 'Estimation', '1', ['round to', 'estimate the value', '1 significant figure', 'to the nearest'], ['estimate', 'approximate', 'significant figures', 'decimal places']),
        ('1.10', 'Limits of accuracy', '1', ['upper bound', 'lower bound', 'limits of accuracy', 'correct to the nearest'], ['accuracy', 'bounds']),
        ('1.11', 'Ratio and proportion', '1', ['in the ratio', 'direct proportion', 'inverse proportion', 'divide in the ratio'], ['ratio', 'proportion', 'share', 'scale']),
        ('1.12', 'Rates', '1', ['average speed', 'km/h', 'rate of flow', 'density is', 'population density'], ['rate', 'per hour', 'speed']),
        ('1.13', 'Percentages', '1', ['percentage increase', 'percentage decrease', 'percentage profit', 'reverse percentage', 'simple interest', 'compound interest'], ['percentage', '%', 'discount', 'profit', 'loss']),
        ('1.14', 'Using a calculator', '1', ['give your answer correct to', 'calculator display'], ['calculator']),
        ('1.15', 'Time', '1', ['24-hour clock', 'timetable', 'hours and minutes'], ['time', 'am', 'pm', 'duration']),
        ('1.16', 'Money', '1', ['exchange rate', 'currency', 'bill', 'cost price', 'selling price'], ['money', 'dollars', 'cost', 'pay']),
        ('1.17', 'Exponential growth and decay', '1', ['exponential growth', 'exponential decay', 'depreciat'], ['growth', 'decay', 'each year']),
        ('1.18', 'Surds', '1', ['surd', 'rationalise the denominator', 'in the form a√'], ['simplify √', '√2', '√3']),
        ('2', 'Algebra and graphs', None, [], ['algebra']),
        ('2.1', 'Introduction to algebra', '2', ['substitute', 'in terms of x', 'write an expression'], ['expression', 'letter', 'term']),
        ('2.2', 'Algebraic manipulation', '2', ['factorise', 'expand and simplify', 'complete the square', 'difference of two squares', 'change the subject', 'rearrange the formula'], ['simplify', 'expand', 'brackets', 'common factor']),
        ('2.3', 'Algebraic fractions', '2', ['algebraic fraction', 'single fraction', 'simplify the fraction'], ['fraction', 'cancel']),
        ('2.4', 'Indices II', '2', ['fractional index', 'negative index', 'laws of indices'], ['index', 'indices', 'power of']),
        ('2.5', 'Equations', '2', ['solve the equation', 'quadratic formula', 'simultaneous equations', 'solve for x', 'roots of the equation'], ['equation', 'solve', 'unknown']),
        ('2.6', 'Inequalities', '2', ['inequality', 'region', 'shade the region', 'linear programming'], ['greater than', 'less than', '≤', '≥']),
        ('2.7', 'Sequences', '2', ['nth term', 'term-to-term', 'sequence', 'subsequent terms'], ['pattern', 'next term', 'first term']),
        ('2.8', 'Proportion', '2', ['directly proportional', 'inversely proportional', 'varies as'], ['proportional', 'constant of proportionality']),
        ('2.9', 'Graphs in practical situations', '2', ['travel graph', 'distance-time graph', 'speed-time graph', 'conversion graph'], ['graph', 'gradient', 'area under']),
        ('2.10', 'Graphs of functions', '2', ['complete the table of values', 'draw the graph of', 'y = x2', 'asymptote', 'cubic graph', 'reciprocal graph'], ['graph', 'plot', 'curve', 'axes', 'intersection']),
        ('2.11', 'Sketching curves', '2', ['sketch the graph', 'turning point', 'stationary point'], ['sketch', 'shape of the curve']),
        ('2.12', 'Differentiation', '2', ['dy/dx', 'differentiate', 'gradient function', 'stationary point', 'maximum or minimum'], ['gradient of the curve', 'derivative']),
        ('2.13', 'Functions', '2', ['f(x)', 'inverse function', 'composite function', 'domain', 'range', 'fg(x)'], ['function', 'mapping']),
        ('3', 'Coordinate geometry', None, [], ['coordinate']),
        ('3.1', 'Coordinates', '3', ['coordinates of the point', 'write down the coordinates'], ['coordinate', 'x-axis', 'y-axis', 'origin']),
        ('3.2', 'Drawing linear graphs', '3', ['draw the line', 'straight line graph'], ['plot', 'line']),
        ('3.3', 'Gradient of linear graphs', '3', ['gradient of the line'], ['gradient', 'slope']),
        ('3.4', 'Length and midpoint', '3', ['midpoint of', 'length of the line segment'], ['midpoint', 'length']),
        ('3.5', 'Equations of linear graphs', '3', ['equation of the line', 'y = mx + c'], ['equation of', 'intercept']),
        ('3.6', 'Parallel lines', '3', ['parallel to the line'], ['parallel']),
        ('3.7', 'Perpendicular lines', '3', ['perpendicular to the line', 'perpendicular bisector'], ['perpendicular']),
        ('4', 'Geometry', None, [], ['geometry', 'shape']),
        ('4.1', 'Geometrical terms', '4', ['isosceles', 'equilateral', 'scalene', 'quadrilateral', 'parallelogram', 'trapezium', 'rhombus', 'polygon', 'pentagon', 'hexagon', 'congruent', 'similar triangles'], ['triangle', 'square', 'rectangle', 'vertex', 'diagonal']),
        ('4.2', 'Geometrical constructions', '4', ['construct', 'compasses', 'locus', 'loci', 'scale drawing', 'bearing'], ['construction', 'arc', 'ruler and']),
        ('4.3', 'Scale drawings', '4', ['scale drawing', 'scale of 1', 'actual distance'], ['scale', 'map']),
        ('4.4', 'Similarity', '4', ['similar', 'scale factor', 'area factor', 'volume factor'], ['enlarge', 'corresponding sides']),
        ('4.5', 'Symmetry', '4', ['line of symmetry', 'rotational symmetry', 'order of rotational symmetry', 'plane of symmetry'], ['symmetry', 'symmetrical']),
        ('4.6', 'Angles', '4', ['angle sum', 'alternate angles', 'corresponding angles', 'co-interior', 'exterior angle', 'interior angle', 'vertically opposite'], ['angle', 'degrees', 'parallel lines']),
        ('4.7', 'Circle theorems I', '4', ['angle in a semicircle', 'angle at the centre', 'tangent', 'cyclic quadrilateral', 'angle in the same segment'], ['circle', 'chord', 'radius', 'circumference']),
        ('4.8', 'Circle theorems II', '4', ['alternate segment', 'intersecting chords', 'tangent from an external point'], ['circle theorem']),
        ('5', 'Mensuration', None, [], ['mensuration']),
        ('5.1', 'Units of measure', '5', ['convert', 'cm2', 'm3', 'millilitres', 'units of'], ['unit', 'metres', 'grams', 'litres']),
        ('5.2', 'Area and perimeter', '5', ['area of the triangle', 'area of the rectangle', 'perimeter of', 'area of a parallelogram', 'area of a trapezium'], ['area', 'perimeter']),
        ('5.3', 'Circles, arcs and sectors', '5', ['arc length', 'area of the sector', 'sector', 'circumference of the circle', 'segment of a circle'], ['circle', 'radius', 'π', 'pi']),
        ('5.4', 'Surface area and volume', '5', ['surface area', 'volume of the cylinder', 'volume of the cone', 'volume of the sphere', 'volume of the prism', 'pyramid', 'hemisphere'], ['volume', 'surface', 'cross-section']),
        ('5.5', 'Compound shapes and parts of shapes', '5', ['compound shape', 'shaded region', 'remaining solid'], ['shaded', 'composite']),
        ('6', 'Trigonometry', None, [], ['trigonometry']),
        ('6.1', "Pythagoras' theorem", '6', ['pythagoras'], ['hypotenuse', 'right-angled triangle']),
        ('6.2', 'Right-angled triangles', '6', ['angle of elevation', 'angle of depression', 'sin', 'cos', 'tan'], ['right-angled', 'opposite', 'adjacent', 'hypotenuse']),
        ('6.3', 'Exact trigonometric values', '6', ['exact value of sin', 'exact value of cos', 'exact value of tan'], ['exact value']),
        ('6.4', 'Trigonometric functions', '6', ['graph of y = sin', 'graph of y = cos', 'graph of y = tan', 'solve the trigonometric equation'], ['sine curve', 'cosine curve', '0° ≤ x ≤ 360°']),
        ('6.5', 'Non-right-angled triangles', '6', ['sine rule', 'cosine rule', '1/2 ab sin'], ['triangle', 'area of the triangle']),
        ('6.6', "Pythagoras' theorem and trigonometry in 3D", '6', ['three dimensions', '3d', 'angle between the line and the plane'], ['cuboid', 'pyramid']),
        ('7', 'Transformations and vectors', None, [], ['transformation', 'vector']),
        ('7.1', 'Transformations', '7', ['reflection in the line', 'rotation about', 'translation by the vector', 'enlargement', 'invariant', 'describe fully the single transformation'], ['transform', 'reflect', 'rotate', 'translate', 'image of']),
        ('7.2', 'Vectors in two dimensions', '7', ['column vector', 'position vector', 'find the vector'], ['vector', 'in terms of a and b']),
        ('7.3', 'Magnitude of a vector', '7', ['magnitude of the vector', '|ab|'], ['magnitude']),
        ('7.4', 'Vector geometry', '7', ['collinear', 'show that the points', 'prove that', 'in terms of a and b'], ['vector geometry', 'parallel vectors']),
        ('8', 'Probability', None, [], ['probability']),
        ('8.1', 'Introduction to probability', '8', ['probability that', 'probability scale', 'at random'], ['probability', 'chance', 'likely']),
        ('8.2', 'Relative and expected frequencies', '8', ['relative frequency', 'expected number', 'how many times would you expect'], ['frequency', 'trials', 'expect']),
        ('8.3', 'Probability of combined events', '8', ['tree diagram', 'possibility diagram', 'without replacement', 'with replacement', 'mutually exclusive', 'independent events'], ['both', 'either', 'combined']),
        ('8.4', 'Conditional probability', '8', ['conditional probability', 'given that'], ['given that']),
        ('9', 'Statistics', None, [], ['statistics', 'data']),
        ('9.1', 'Classifying statistical data', '9', ['discrete data', 'continuous data', 'qualitative', 'quantitative'], ['data', 'categories']),
        ('9.2', 'Interpreting statistical data', '9', ['make a comment', 'compare the', 'draw an inference', 'interpret the'], ['interpret', 'conclusion']),
        ('9.3', 'Averages and measures of spread', '9', ['mean', 'median', 'mode', 'range', 'interquartile range', 'quartile', 'modal class', 'estimate of the mean'], ['average', 'spread']),
        ('9.4', 'Statistical charts and diagrams', '9', ['bar chart', 'pie chart', 'pictogram', 'stem-and-leaf', 'box-and-whisker', 'frequency polygon'], ['chart', 'diagram', 'graph', 'table']),
        ('9.5', 'Scatter diagrams', '9', ['scatter diagram', 'line of best fit', 'correlation'], ['scatter', 'positive correlation', 'negative correlation']),
        ('9.6', 'Cumulative frequency diagrams', '9', ['cumulative frequency'], ['cumulative']),
        ('9.7', 'Histograms', '9', ['histogram', 'frequency density', 'unequal class widths'], ['histogram', 'class width']),
    ],
    '0606': [
        ('1', 'Functions', None, ['f(x)', 'inverse function', 'composite function', 'one-one function', 'domain', 'range', 'modulus function', '|x|'], ['function', 'mapping', 'graph of y =']),
        ('2', 'Quadratic functions', None, ['complete the square', 'discriminant', 'b2 - 4ac', 'maximum or minimum value', 'quadratic function', 'roots are real'], ['quadratic', 'parabola', 'vertex']),
        ('3', 'Factors of polynomials', None, ['remainder theorem', 'factor theorem', 'cubic polynomial', 'divide the polynomial'], ['polynomial', 'factorise', 'remainder']),
        ('4', 'Equations, inequalities and graphs', None, ['solve the inequality', 'modulus inequality', 'sketch the graph of y = |', 'cubic inequality'], ['inequality', 'solve', 'sketch']),
        ('5', 'Simultaneous equations', None, ['simultaneous equations', 'solve the simultaneous'], ['simultaneous', 'two unknowns']),
        ('6', 'Logarithmic and exponential functions', None, ['logarithm', 'log', 'ln', 'ex', 'laws of logarithms', 'exponential function', 'base e'], ['exponential', 'logarithmic']),
        ('7', 'Straight-line graphs', None, ['y = mx + c', 'reduce to linear form', 'plot a straight line graph', 'gradient and intercept', 'midpoint and length'], ['straight line', 'gradient', 'intercept', 'linear form']),
        ('8', 'Coordinate geometry of the circle', None, ['equation of the circle', '(x - a)2 + (y - b)2', 'centre and radius'], ['circle', 'centre', 'radius']),
        ('9', 'Circular measure', None, ['radian', 'arc length', 'area of the sector', 'circular measure'], ['sector', 'arc', 'radius', 'angle in radians']),
        ('10', 'Trigonometry', None, ['sec', 'cosec', 'cot', 'trigonometric identity', 'amplitude and period', 'sin2', 'cos2', 'solve the trigonometric equation'], ['trigonometric', 'sine', 'cosine', 'tangent', 'degrees', 'radians']),
        ('11', 'Permutations and combinations', None, ['permutation', 'combination', 'nPr', 'nCr', 'arrangements', 'how many different ways'], ['arrange', 'select', 'order matters']),
        ('12', 'Series', None, ['binomial expansion', 'arithmetic progression', 'geometric progression', 'sum to infinity', 'common difference', 'common ratio', 'nth term of the series'], ['series', 'expansion', 'progression', 'sum of the first']),
        ('13', 'Vectors in two dimensions', None, ['position vector', 'unit vector', 'magnitude of the vector', 'relative velocity', 'column vector'], ['vector', 'displacement', 'velocity vector']),
        ('14', 'Calculus', None, ['differentiate', 'dy/dx', 'integrate', 'definite integral', 'chain rule', 'product rule', 'quotient rule', 'stationary point', 'rate of change', 'area under the curve', 'd2y/dx2'], ['derivative', 'integral', 'gradient', 'tangent', 'normal to the curve']),
    ],
}


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "subjects", sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true"))
    )
    op.add_column(
        "subjects",
        sa.Column(
            "qualification_level",
            postgresql.ENUM(
                "igcse", "o_level", "as_level", "a_level", name="qualificationlevel", create_type=False
            ),
            nullable=True,
        ),
    )
    op.add_column("subjects", sa.Column("syllabus_version", sa.String(), nullable=True))
    op.add_column("subjects", sa.Column("source_url", sa.String(), nullable=True))

    # Not pre-created via `.create(...)`: `op.create_table` below creates the
    # backing `papertier` type implicitly the first (and only) time this enum
    # column is used, exactly as `0023_invites` does for `inviterole`. Calling
    # `.create()` here too double-creates the type and fails with "type
    # papertier already exists".
    tier = postgresql.ENUM("core", "extended", name="papertier")

    op.create_table(
        "syllabus_papers",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")
        ),
        sa.Column(
            "board",
            postgresql.ENUM("caie", "edexcel", "oxford_aqa", name="examboard", create_type=False),
            nullable=False,
            server_default=sa.text("'caie'::examboard"),
        ),
        sa.Column("subject_code", sa.String(), sa.ForeignKey("subjects.code"), nullable=False),
        sa.Column("paper_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tier", tier, nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("total_marks", sa.Integer(), nullable=False),
        sa.Column("practical", sa.Boolean(), nullable=False),
        sa.Column("source_document", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("syllabus_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("board", "subject_code", "paper_number", name="uq_syllabus_papers_identity"),
    )

    op.create_table(
        "subject_topics",
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")
        ),
        sa.Column(
            "board",
            postgresql.ENUM("caie", "edexcel", "oxford_aqa", name="examboard", create_type=False),
            nullable=False,
            server_default=sa.text("'caie'::examboard"),
        ),
        sa.Column("subject_code", sa.String(), sa.ForeignKey("subjects.code"), nullable=False),
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("subject_topics.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("strong", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("keywords", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("board", "subject_code", "code", name="uq_subject_topics_identity"),
    )
    op.create_index("ix_subject_topics_subject", "subject_topics", ["board", "subject_code"])

    _backfill()


def _backfill() -> None:
    """Insert the catalogue. Idempotent: skips a subject/paper/topic that already exists."""
    bind = op.get_bind()

    for subject in SUBJECTS:
        bind.execute(
            sa.text(
                "INSERT INTO subjects (code, name, board, active, qualification_level, "
                "syllabus_version, source_url) "
                "VALUES (:code, :name, 'caie', true, 'igcse', :version, :source_url) "
                "ON CONFLICT (code) DO UPDATE SET "
                "qualification_level = EXCLUDED.qualification_level, "
                "syllabus_version = EXCLUDED.syllabus_version, "
                "source_url = EXCLUDED.source_url"
            ),
            {
                "code": subject["code"],
                "name": subject["name"],
                "version": subject["syllabus_version"],
                "source_url": subject["source_url"],
            },
        )

    for paper in PAPERS:
        bind.execute(
            sa.text(
                "INSERT INTO syllabus_papers (board, subject_code, paper_number, name, tier, "
                "duration_minutes, total_marks, practical, source_document, source_url, syllabus_version) "
                "VALUES (:board, :subject_code, :paper_number, :name, "
                "CAST(:tier AS papertier), :duration_minutes, :total_marks, :practical, "
                ":source_document, :source_url, :syllabus_version) "
                "ON CONFLICT ON CONSTRAINT uq_syllabus_papers_identity DO NOTHING"
            ),
            paper,
        )

    for subject_code, rows in TOPICS.items():
        ids: dict[str, str] = {}
        # Parents first: a child's `parent_id` must reference a row that exists,
        # and the source file lists every parent before its own subtopics.
        for code, name, parent_code, strong, keywords in rows:
            new_id = bind.execute(
                sa.text(
                    "INSERT INTO subject_topics (board, subject_code, parent_id, code, name, strong, keywords) "
                    "VALUES ('caie', :subject_code, CAST(:parent_id AS uuid), :code, :name, "
                    "CAST(:strong AS jsonb), CAST(:keywords AS jsonb)) "
                    "ON CONFLICT ON CONSTRAINT uq_subject_topics_identity DO NOTHING "
                    "RETURNING id"
                ),
                {
                    "subject_code": subject_code,
                    "parent_id": ids.get(parent_code) if parent_code else None,
                    "code": code,
                    "name": name,
                    "strong": _json.dumps(strong),
                    "keywords": _json.dumps(keywords),
                },
            ).scalar()
            if new_id is not None:
                ids[code] = str(new_id)
            else:
                # Re-run: the row already exists (ON CONFLICT DO NOTHING returned
                # nothing), but a later child in this same subject may still need
                # its parent's id, so look it up rather than leaving a gap.
                existing_id = bind.execute(
                    sa.text(
                        "SELECT id FROM subject_topics "
                        "WHERE board = 'caie' AND subject_code = :subject_code AND code = :code"
                    ),
                    {"subject_code": subject_code, "code": code},
                ).scalar()
                if existing_id is not None:
                    ids[code] = str(existing_id)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_subject_topics_subject", table_name="subject_topics")
    op.drop_table("subject_topics")
    op.drop_table("syllabus_papers")
    op.drop_column("subjects", "source_url")
    op.drop_column("subjects", "syllabus_version")
    op.drop_column("subjects", "qualification_level")
    op.drop_column("subjects", "active")
    op.execute("DROP TYPE IF EXISTS papertier")
