import { describe, expect, it } from "vitest"
import { manifest } from "../../vite/manifest.ts"

/*
 * Packet A5 — pins the manifest members the audit dossier's `manifest-*`
 * findings asked for, now that `manifest` is a plain, importable object
 * (`vite/manifest.ts`) rather than only reachable through `vite.config.ts`.
 * See that module's own docstring for why each member exists.
 */

describe("manifest identity and layout", () => {
  it("id is a stable install identity independent of start_url", () => {
    expect(manifest.id).toBe("/")
  })

  it("dir states the one text direction this product ships", () => {
    expect(manifest.dir).toBe("ltr")
  })

  it("orientation is unlocked", () => {
    expect(manifest.orientation).toBe("any")
  })

  it("prefer_related_applications is false — there is no native app to prefer", () => {
    expect(manifest.prefer_related_applications).toBe(false)
  })

  it("display_override degrades standalone before falling back further", () => {
    expect(manifest.display_override).toEqual(["standalone", "minimal-ui"])
  })

  it("categories genuinely describe this product", () => {
    expect(manifest.categories).toEqual(["education", "productivity"])
  })
})

describe("manifest capability members", () => {
  it("launch_handler focuses the existing instance rather than opening a second window", () => {
    expect(manifest.launch_handler).toEqual({ client_mode: "navigate-existing" })
  })

  it("handle_links prefers opening same-origin links inside the installed app", () => {
    expect(manifest.handle_links).toBe("preferred")
  })

  it("protocol_handlers registers web+lemely://join/<code>", () => {
    expect(manifest.protocol_handlers).toEqual([{ protocol: "web+lemely", url: "/join/%s" }])
  })

  it("edge_side_panel fits the app's own max-w-100 (400px) column", () => {
    expect(manifest.edge_side_panel).toEqual({ preferred_width: 400 })
  })

  it("scope_extensions associates the staging origin", () => {
    expect(manifest.scope_extensions).toEqual([{ origin: "https://staging.lemelyig.com" }])
  })

  it("note_taking's new_note_url lands on Practice", () => {
    expect(manifest.note_taking).toEqual({ new_note_url: "/student/practice" })
  })
})

describe("manifest.shortcuts", () => {
  it("has exactly the three jump-list entries", () => {
    expect(manifest.shortcuts).toHaveLength(3)
    expect(manifest.shortcuts.map((s) => s.name)).toEqual(["Mark a paper", "Dashboard", "Notifications"])
  })

  it("every shortcut carries a 96x96 PNG icon", () => {
    for (const shortcut of manifest.shortcuts) {
      expect(shortcut.icons).toHaveLength(1)
      expect(shortcut.icons[0].sizes).toBe("96x96")
      expect(shortcut.icons[0].type).toBe("image/png")
    }
  })
})

describe("manifest.screenshots", () => {
  it("has one wide and one narrow form factor, generated by manifest_screenshots.mjs", () => {
    const formFactors = manifest.screenshots.map((s) => s.form_factor).toSorted()
    expect(formFactors).toEqual(["narrow", "wide"])
  })

  it("every screenshot is a real JPEG under public/screenshots/", () => {
    for (const shot of manifest.screenshots) {
      expect(shot.src).toMatch(/^screenshots\/.+\.jpg$/)
      expect(shot.type).toBe("image/jpeg")
      expect(shot.sizes).toMatch(/^\d+x\d+$/)
    }
  })
})

describe("manifest.widgets", () => {
  it("declares the Streak widget backed by the Adaptive Card templates", () => {
    expect(manifest.widgets).toEqual([
      {
        name: "Streak",
        tag: "lemely-streak",
        ms_ac_template: "widgets/streak.json",
        data: "widgets/streak-data.json",
        description: "Your study streak and next session",
        screenshots: [
          { src: "screenshots/dashboard-narrow.jpg", sizes: "780x1688", label: "Streak widget preview" },
        ],
      },
    ])
  })
})
