import { describe, expect, it } from "vitest"
import { buildManifest } from "../../vite/manifest.ts"

/*
 * Packet A5 — pins the manifest members the audit dossier's `manifest-*`
 * findings asked for, now that `buildManifest` is a plain, importable
 * function (`vite/manifest.ts`) rather than only reachable through
 * `vite.config.ts`. See that module's own docstring for why each member
 * exists. `manifest` here is `buildManifest("production")` — the mode every
 * real build uses except the one CI passes explicitly for the staging
 * deploy job (see `manifest mode gating`, below, and `buildManifest`'s own
 * docstring for why `scope_extensions` is the one member that varies).
 */

const manifest = buildManifest("production")

describe("manifest identity and layout", () => {
  it("id is a stable install identity independent of start_url", () => {
    expect(manifest.id).toBe("/")
  })

  it("dir states the one text direction this product ships", () => {
    expect(manifest.dir).toBe("ltr")
  })

  it("orientation is unlocked", () => {
    expect(manifest.orientation).toBe("any")
  })

  it("prefer_related_applications is false — there is no native app to prefer", () => {
    expect(manifest.prefer_related_applications).toBe(false)
  })

  it("display_override degrades standalone before falling back further", () => {
    expect(manifest.display_override).toEqual(["standalone", "minimal-ui"])
  })

  it("categories genuinely describe this product", () => {
    expect(manifest.categories).toEqual(["education", "productivity"])
  })
})

describe("manifest capability members", () => {
  it("launch_handler focuses the existing instance rather than opening a second window", () => {
    expect(manifest.launch_handler).toEqual({ client_mode: "navigate-existing" })
  })

  it("handle_links prefers opening same-origin links inside the installed app", () => {
    expect(manifest.handle_links).toBe("preferred")
  })

  it("protocol_handlers registers web+lemely://join/<code>", () => {
    expect(manifest.protocol_handlers).toEqual([{ protocol: "web+lemely", url: "/join/%s" }])
  })

  it("edge_side_panel fits the app's own max-w-100 (400px) column", () => {
    expect(manifest.edge_side_panel).toEqual({ preferred_width: 400 })
  })

  it("note_taking's new_note_url lands on the dashboard, an always-mounted path", () => {
    // Not `/student/practice`: `student/data.ts`'s own comment already
    // documents that path as unmounted ("linking it would manufacture a
    // dead end") — `/student` is the safe, always-real fallback.
    expect(manifest.note_taking).toEqual({ new_note_url: "/student" })
  })
})

describe("manifest mode gating", () => {
  it("omits scope_extensions from a production build", () => {
    expect(buildManifest("production").scope_extensions).toBeUndefined()
  })

  it("includes the staging origin only in a staging build", () => {
    expect(buildManifest("staging").scope_extensions).toEqual([
      { origin: "https://staging.lemelyig.com" },
    ])
  })
})

describe("manifest.shortcuts", () => {
  it("has exactly the three jump-list entries", () => {
    expect(manifest.shortcuts).toHaveLength(3)
    expect(manifest.shortcuts.map((s) => s.name)).toEqual(["Mark a paper", "Dashboard", "Notifications"])
  })

  it("every shortcut carries a 96x96 PNG icon", () => {
    for (const shortcut of manifest.shortcuts) {
      expect(shortcut.icons).toHaveLength(1)
      expect(shortcut.icons[0].sizes).toBe("96x96")
      expect(shortcut.icons[0].type).toBe("image/png")
    }
  })
})

describe("manifest.screenshots", () => {
  it("has one wide and one narrow form factor, generated by manifest_screenshots.mjs", () => {
    const formFactors = manifest.screenshots.map((s) => s.form_factor).toSorted()
    expect(formFactors).toEqual(["narrow", "wide"])
  })

  it("every screenshot is a real JPEG under public/screenshots/", () => {
    for (const shot of manifest.screenshots) {
      expect(shot.src).toMatch(/^screenshots\/.+\.jpg$/)
      expect(shot.type).toBe("image/jpeg")
      expect(shot.sizes).toMatch(/^\d+x\d+$/)
    }
  })
})

describe("manifest.share_target", () => {
  // Packet A6. The `/share-target` POST body is handled by
  // `src/sw/shareTarget.ts`'s `handleShareTargetFetch`, which reads the file
  // under this exact field name (`formData.get("scan")`) — the two have to
  // agree, and only this member's declaration is checked by the OS.
  it("POSTs multipart form data to /share-target with the file under the scan field", () => {
    expect(manifest.share_target.action).toBe("/share-target")
    expect(manifest.share_target.method).toBe("POST")
    expect(manifest.share_target.enctype).toBe("multipart/form-data")
    expect(manifest.share_target.params.files).toHaveLength(1)
    expect(manifest.share_target.params.files[0].name).toBe("scan")
  })

  it("accepts images and PDFs — the two scan formats CorrectPaper already takes", () => {
    expect(manifest.share_target.params.files[0].accept).toEqual(["image/*", "application/pdf"])
  })
})

describe("manifest.file_handlers", () => {
  // The File Handling API counterpart to share_target: an OS "open with"
  // launch instead of an OS share sheet, routed to the same /file-handler
  // redirect (`routes.tsx`) into the same marking flow.
  it("registers exactly one handler, routed through /file-handler", () => {
    expect(manifest.file_handlers).toHaveLength(1)
    expect(manifest.file_handlers[0].action).toBe("/file-handler")
  })

  it("accepts the same two scan formats as share_target, by extension", () => {
    expect(manifest.file_handlers[0].accept).toEqual({
      "image/*": [".png", ".jpg", ".jpeg"],
      "application/pdf": [".pdf"],
    })
  })
})

describe("manifest.widgets", () => {
  it("declares the Streak widget backed by the Adaptive Card templates", () => {
    expect(manifest.widgets).toEqual([
      {
        name: "Streak",
        tag: "lemely-streak",
        ms_ac_template: "widgets/streak.json",
        data: "widgets/streak-data.json",
        description: "Your study streak and next session",
        screenshots: [
          { src: "screenshots/dashboard-narrow.jpg", sizes: "780x1688", label: "Streak widget preview" },
        ],
      },
    ])
  })
})
